
version: "3"
services: 
  supplier-hub-app:
 
    image: docker-supplier-hub:latest
    restart: always
    build: .
    ports:
      - 8000-8999:8080 
    environment:
      MYSQL_HOST: some-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root/123
      MYSQL_PORT: 3306
  mysqldb: 
    container_name: some-mysql
    image: mysql:8.0.28
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports: 
     - 9000:3306   
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_ROOT_PASSWORD: root/123
